"""booktabs LaTeX table writer. The best value of each numeric column can be bolded."""
from __future__ import annotations

from pathlib import Path

import numpy as np

from .config import TABLES


def esc(s) -> str:
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#")):
        s = s.replace(a, b)
    return s


def fmt(v, nd: int = 2) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "--"
    if isinstance(v, (int, np.integer)):
        return f"{int(v):,}"
    if isinstance(v, (float, np.floating)):
        return f"{v:.{nd}f}"
    return str(v)


def write_table(name: str, header: list[str], rows: list[list], *, best: dict[int, str] | None = None,
                std: dict[int, list] | None = None, nd: int | dict[int, int] = 2, align: str | None = None,
                caption_note: str | None = None, out_dir: Path | None = None, raw_cols: set[int] = frozenset(),
                midrule_after: set[int] = frozenset()) -> Path:
    """rows: list of rows; column 0 is the label.

    best: {col: "min" | "max"} → bold the best numeric value in that column.
    std:  {col: [std per row]} → cell rendered as "mean ± std".
    raw_cols: columns whose strings are already LaTeX (not escaped).
    """
    best = best or {}
    std = std or {}
    winners = {}
    for c, mode in best.items():
        vals = [(r[c], i) for i, r in enumerate(rows)
                if isinstance(r[c], (int, float, np.floating)) and not np.isnan(r[c])]
        if vals:
            target = min(v for v, _ in vals) if mode == "min" else max(v for v, _ in vals)
            winners[c] = {i for v, i in vals if np.isclose(v, target)}
    lines = [f"% generated by the pipeline — do not edit ({name})"]
    if caption_note:
        lines.append(f"% {caption_note}")
    align = align or ("l" + "r" * (len(header) - 1))
    lines += [rf"\begin{{tabular}}{{{align}}}", r"\toprule", " & ".join(header) + r" \\", r"\midrule"]
    for i, r in enumerate(rows):
        cells = []
        for c, v in enumerate(r):
            ndc = nd.get(c, 2) if isinstance(nd, dict) else nd
            if isinstance(v, str):
                s = v if (c in raw_cols) else esc(v)
            else:
                s = fmt(v, ndc)
                if c in std and std[c][i] is not None:
                    s += rf" $\pm$ {fmt(float(std[c][i]), ndc)}"
            if i in winners.get(c, ()):
                s = rf"\textbf{{{s}}}"
            cells.append(s)
        lines.append(" & ".join(cells) + r" \\")
        if i in midrule_after:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out_dir = out_dir or TABLES
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{name}.tex"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
