"""Turn results/*.json into LaTeX macros → paper/tables/numbers.tex.

In the paper every number is written as \\res{key}; no result is typed by hand (spec §10.2).
Keys that do not exist yet (e.g. test results before 06_final_test.py has run) render as "??".
"""
from __future__ import annotations

import pandas as pd

from utils.config import RESULTS, TABLES, load_config, read_json

HEADER = r"""% generated by src/07_paper_numbers.py — do not edit
\makeatletter
\providecommand{\res}[1]{\ifcsname res@#1\endcsname\csname res@#1\endcsname\else\textbf{??}\fi}
\makeatother
"""


def main() -> None:
    cfg = load_config()
    out: dict[str, str] = {}

    def put(key: str, v, nd: int | None = 2) -> None:
        if v is None:
            return
        if isinstance(v, bool):
            s = "yes" if v else "no"
        elif isinstance(v, int):
            s = f"{v:,}".replace(",", "{,}")
        elif isinstance(v, float):
            s = f"{v:.{nd}f}"
        elif nd is None:  # already LaTeX
            s = str(v)
        else:
            s = str(v).replace("_", r"\_").replace("%", r"\%")
        out[key] = s

    def pval(key: str, p: float) -> None:
        out[key] = "$<$0.001" if p < 0.001 else f"{p:.3f}"

    def metrics(prefix: str, r: dict) -> None:
        for m in ("mae", "rmse", "r2", "peak_mae"):
            name = m.replace("_mae", "")
            put(f"{prefix}.{name}", r[f"{m}_mean"])
            put(f"{prefix}.{name}Std", r[f"{m}_std"])

    # ---- config
    ev, f, p = cfg["evaluation"], cfg["features"], cfg["period"]
    put("cfg.threshold", float(ev["peak_mae_threshold_min"]), 1)
    put("cfg.onset", float(ev["onset_delta_min"]), 0)
    put("cfg.bootstrapB", int(ev["bootstrap_B"]))
    put("cfg.hacLags", int(ev["hac_maxlags"]))
    put("cfg.peakStart", f["peak_start"])
    put("cfg.peakEnd", f["peak_end"])
    for k in ("train_start", "train_end", "test_start", "test_end"):
        put(f"cfg.{k.replace('_', '')}", str(p[k].date()))
    for role, (a, b) in cfg["m04a"]["segments"].items():
        put(f"cfg.seg.{role}", rf"\texttt{{{a}}}\,$\rightarrow$\allowbreak\,\texttt{{{b}}}", None)

    # ---- data
    rep = read_json(RESULTS / "dataset_report.json")
    for k in ("grid_rows", "dropped_y_nan", "dropped_feature_nan", "final_rows", "rows_train", "rows_test",
              "days_train", "days_test"):
        put(f"data.{k.replace('_', '')}", int(rep[k]))
    put("data.ffilled", int(sum(rep["ffilled_values"].values())))
    put("data.validPct", 100 * rep["raw_coverage"]["target"]["valid_frac"], 2)
    put("data.upValidPct", 100 * rep["raw_coverage"]["upstream"]["valid_frac"], 2)
    gaps = pd.read_csv(RESULTS / "download_gaps.csv")
    put("data.missingFiles", int(len(gaps)))

    eda = read_json(RESULTS / "eda.json")
    for k, v in eda["summary"]["y"].items():
        put(f"y.{k}", v if k != "count" else int(v))
    for k, v in eda["shares"].items():
        put(f"share.{k.replace('_rows', '')}", 100 * v, 1)
    for d in eda["rank"]:
        put(f"r.{d['feature']}", d["abs_pearson"])
        put(f"rho.{d['feature']}", abs(d["spearman"]))
    put("r.top", ", ".join(rf"\texttt{{{d['feature']}}}".replace("_", r"\_") for d in eda["rank"][:5]), None)
    for k, v in eda["vif_collinear_block"].items():
        put(f"vifBlock.{k}", v, 1)
    put("corr.now.lag", eda["corr"]["tt_now"]["tt_lag15"])
    put("corr.now.up", eda["corr"]["tt_now"]["up_tt_now"])
    put("rain.offpeak", eda["rain"]["rain_effect_offpeak_min"])
    put("rain.peak", eda["rain"]["rain_effect_peak_min"])
    put("profile.workdayPeakSlot", eda["peak_window_check"]["workday_median_max_slot"])
    wd = eda["profile"]["workday"]
    nwd = eda["profile"]["nonworkday"]
    put("profile.workdayPeakMedian", max(v["median"] for v in wd.values()))
    k_n = max(nwd, key=lambda s: nwd[s]["median"])
    put("profile.nonworkdayPeakSlot", k_n)
    put("profile.nonworkdayPeakMedian", nwd[k_n]["median"])

    # ---- CV
    base, ridge, var = (read_json(RESULTS / n) for n in ("cv_baselines.json", "cv_ridge.json", "cv_variants.json"))
    sel, tests = read_json(RESULTS / "selected.json"), read_json(RESULTS / "cv_tests.json")
    kB = f"B_k{sel['topk']}"
    for name, r in (("mean", base["mean"]), ("persistence", base["persistence"]), ("profile", base["profile"]),
                    ("ols", base["ols_tt_now"]), ("lgbm", base["lgbm_A"]), ("ridgeA", ridge["A"]["best"]),
                    ("ridgeB", ridge[kB]["best"]), ("ridgeC", ridge["C"]["best"]),
                    ("lasso", var["lasso"]["best"]), ("enet", var["enet"]["best"]),
                    ("logy", var["ridge_logy"]["best"]), ("olsC", var["ols_C"]["best"])):
        metrics(f"cv.{name}", r)
    for k in cfg["cv"]["topk_sensitivity"]:
        metrics(f"cv.ridgeBk{k}", ridge[f"B_k{k}"]["best"])
    put("sel.alphaC", f"{sel['ridge_alpha']['C']:.4g}")
    put("sel.alphaA", f"{sel['ridge_alpha']['A']:.4g}")
    put("sel.alphaB", f"{sel['ridge_alpha'][kB]:.4g}")
    put("sel.topk", int(sel["topk"]))
    put("sel.lgbmLeaves", int(sel["lgbm"]["num_leaves"]))
    put("sel.lgbmLr", f"{sel['lgbm']['learning_rate']:g}")
    put("sel.lassoAlpha", f"{var['lasso']['best']['alpha']:.4g}")
    put("sel.cvMeets", bool(sel["cv_meets_threshold"]))
    stable = set.intersection(*(set(s) for s in ridge[kB]["selected_features_per_fold"]))
    put("sel.topkStable", ", ".join(rf"\texttt{{{c}}}".replace("_", r"\_") for c in
                                     ridge[kB]["selected_features_per_fold"][-1]), None)
    put("sel.topkNStable", int(len(stable)))
    short = {"lgbm_A_vs_ridge_C": "lgbm", "persistence_vs_ridge_C": "persistence", "ridge_A_vs_ridge_C": "A",
             f"ridge_{kB}_vs_ridge_C": "B", "lasso_vs_ridge_C": "lasso", "enet_vs_ridge_C": "enet",
             "ridge_logy_vs_ridge_C": "logy"}
    short.update({f"ridge_C_minus_{g}_vs_ridge_C": f"minus.{g}"
                  for g in ("lags", "upstream", "calendar", "slot", "caltime", "weather")})
    for k, name in short.items():
        t = tests[k]
        put(f"ttest.{name}.diff", t["mean_diff"], 3)
        put(f"ttest.{name}.absdiff", abs(t["mean_diff"]), 3)
        put(f"ttest.{name}.t", t["t"])
        pval(f"ttest.{name}.p", t["p"])

    # ---- coefficients / hypotheses
    co = read_json(RESULTS / "coefficients.json")
    put("coef.rsq", co["r2"])
    put("coef.gap", co["ridge_ols_max_abs_coef_diff"], 3)
    put("coef.gapFeature", rf"\texttt{{{co['ridge_ols_max_diff_feature']}}}".replace("_", r"\_"), None)
    put("coef.nVifFlag", int(co["n_vif_flagged"]))
    put("coef.nFeat", int(co["n_features"]))
    put("coef.gapOk", co["ridge_ols_max_abs_coef_diff_nonslot_lowvif"], 3)
    put("data.nfeatC", int(len(ridge["C"]["features"])))
    put("data.nSlot", int(len(co["slot_effects"])))
    c3 = co["hypotheses"]["H3"]
    put("hyp.H3.contrast", c3["workday_peak_contrast"]["estimate_min"])
    pval("hyp.H3.contrastP", c3["workday_peak_contrast"]["p_hac"])
    wd_fx = [e for e in co["slot_effects"] if e["is_workday"] == 1]
    nwd_fx = [e for e in co["slot_effects"] if e["is_workday"] == 0]
    top_wd, top_nwd = max(wd_fx, key=lambda e: e["effect_min"]), max(nwd_fx, key=lambda e: e["effect_min"])
    put("slotfx.wdTime", top_wd["time"]); put("slotfx.nwdTime", top_nwd["time"])
    put("slotfx.wdRange", top_wd["effect_min"] - min(e["effect_min"] for e in wd_fx), 1)
    put("slotfx.nwdRange", top_nwd["effect_min"] - min(e["effect_min"] for e in nwd_fx), 1)
    put("coef.seRatio", co["max_se_ratio_hac_vs_ols"], 1)
    for d in co["coefficients"]:
        k = d["feature"]
        put(f"coef.{k}.beta", d["beta_std"], 3)
        put(f"coef.{k}.raw", d["beta_raw"], 3)
        put(f"coef.{k}.lo", d["ci_low"], 3)
        put(f"coef.{k}.hi", d["ci_high"], 3)
        put(f"coef.{k}.vif", d["vif"], 1)
        pval(f"coef.{k}.p", d["p_hac"])
        for L in co["hac_sensitivity"]:
            pval(f"coef.{k}.p{L}", d[f"p_hac{L}"])
    for h, v in co["hypotheses"].items():
        put(f"hyp.{h}.verdict", v["provisional_verdict"])
        put(f"hyp.{h}.diff", v["ablation_delta_mae_min"], 3)
        pval(f"hyp.{h}.p", v["ablation_p"])
        put(f"hyp.{h}.folds", int(v["ablation_folds_improved"]))

    # ---- final test (only after the one-time run)
    tr_path = RESULTS / "test_results.json"
    if tr_path.exists():
        tr = read_json(tr_path)
        names = {"mean": "mean", "persistence": "persistence", "profile": "profile", "ols_tt_now": "ols",
                 "lgbm_A": "lgbm", "ridge_A": "ridgeA", "ridge_B": "ridgeB", "ridge_C": "ridgeC",
                 "ridge_C_logy": "logy"}
        for k, n in names.items():
            for m, v in tr["metrics"][k].items():
                if m in ("mae", "rmse", "r2", "peak_mae"):
                    put(f"test.{n}.{m.replace('_mae', '')}", v)
        th = tr["threshold"]
        put("test.peakLo", th["peak_mae_ci95"][0])
        put("test.peakHi", th["peak_mae_ci95"][1])
        put("test.meets", "meets" if th["meets_threshold"] else "does not meet")
        put("test.n", int(tr["n_test"]))
        put("test.topDaysSqShare", 100 * tr["share_of_sq_error_top5_days"], 0)
        put("test.residMean", tr["residual_mean"])
        for k, b in tr["bootstrap"].items():
            n = k.replace("_minus_ridge_C", "").replace("_peak", "")
            n = names[n] + (".peak" if k.endswith("_peak") else "")
            put(f"boot.{n}.diff", b["diff"], 3)
            put(f"boot.{n}.lo", b["ci_low"], 3)
            put(f"boot.{n}.hi", b["ci_high"], 3)
        for s, d in tr["slices"].items():
            put(f"slice.{s}.n", int(d["n"]))
            for k, v in d.items():
                if k != "n" and v is not None:
                    put(f"slice.{s}.{names[k]}", v)
        for i, e in enumerate(tr["top_errors"], 1):
            put(f"err.{i}.T", e["T"][:16])
            put(f"err.{i}.error", e["error"], 1)
        put("err.worstDay", tr["worst_days"][0]["date"])

    lines = [HEADER]
    for k in sorted(out):
        lines.append(rf"\expandafter\def\csname res@{k}\endcsname{{{out[k]}}}")
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"numbers.tex: {len(out)} macros" + ("" if tr_path.exists() else " (test results not available yet)"))


if __name__ == "__main__":
    main()
